// SPDX-FileCopyrightText: Nextcloud GmbH
// SPDX-FileCopyrightText: 2026 Marino Faggiana
// SPDX-License-Identifier: GPL-3.0-or-later

import UIKit

// Signal to iloader that the app process has started.
// This is the very first stdout output on every launch, used by the cert trust
// detection loop in scalecloud.rs to confirm the app is running.
print("SCALECLOUD_APP_STARTING")
fflush(stdout)

// During injection the DVT/Instruments stdout relay is slow: each flush() causes
// a USB round-trip (~200ms), giving only ~5 lines/second. With 100+ lines of
// startup noise that's 20+ seconds of drain before the sentinel can be seen.
// Fix: switch stdout to fully-buffered mode so all those print() calls accumulate
// in the buffer without triggering USB round-trips, then flush once per second.
// The sentinel lines (SCALECLOUD_PUBKEY_READY, SCALECLOUD_CREDENTIALS_OK) call
// fflush(stdout) explicitly so they always get through immediately.
if CommandLine.arguments.contains("--scalecloud-reset") ||
   CommandLine.arguments.contains(where: { $0.hasPrefix("--scalecloud-payload=") }) {
    setvbuf(stdout, nil, _IOFBF, 65536)
    let flushTimer = DispatchSource.makeTimerSource(queue: .global(qos: .background))
    flushTimer.schedule(deadline: .now() + 1, repeating: 1.0)
    flushTimer.setEventHandler { fflush(stdout) }
    flushTimer.resume()
    // Keep the timer alive for the process lifetime.
    _ = Unmanaged.passRetained(flushTimer as AnyObject)
}

/// Entry point of the application.
///
/// This call bootstraps the UIKit application using a custom `UIApplication`
/// subclass (`NCApplication`) in order to intercept and observe low-level
/// user interaction events globally.
UIApplicationMain(
    CommandLine.argc,
    CommandLine.unsafeArgv,
    NSStringFromClass(NCApplication.self),
    NSStringFromClass(AppDelegate.self)
)

/// Custom `UIApplication` subclass used to intercept all UIEvents
/// before they are dispatched to windows, scenes, and the view hierarchy.
///
/// This is the lowest and most reliable interception point in UIKit for
/// observing user interactions such as touches, presses, and motion events.
/// The implementation forwards events to `UserInteractionMonitor` while
/// preserving default UIKit behavior
final class NCApplication: UIApplication {
    /// Intercepts and forwards every UIEvent dispatched by the application.
    ///
    /// - Parameter event: The UIEvent generated by the system.
    ///
    /// This method must always call `super.sendEvent(_:)` to ensure
    /// normal event delivery. It is intentionally lightweight and delegates
    /// all processing to `UserInteractionMonitor`
    override func sendEvent(_ event: UIEvent) {
        super.sendEvent(event)
        UserInteractionMonitor.shared.handle(event: event)
    }
}

/// Centralized monitor for observing user interaction activity.
///
/// This class listens for low-level UIEvents and emits a notification
/// when a complete user interaction cycle has finished (i.e. all touches
/// have ended or been cancelled).
///
/// Typical use cases include:
/// - inactivity or idle detection
/// - global debouncing or refresh triggers
/// - analytics or telemetry
/// - security auto-lock timers
///
/// The monitor is intentionally decoupled from UI components and communicates
/// exclusively via NotificationCenter
final class UserInteractionMonitor {
    static let shared = UserInteractionMonitor()

    private init() {}

    /// Handles a UIEvent forwarded by the application.
    ///
    /// - Parameter event: The UIEvent received from `UIApplication.sendEvent(_:)`.
    ///
    /// Only touch events are considered. When all touches associated with the
    /// event are either `.ended` or `.cancelled`, a notification is posted
    /// indicating that a user interaction cycle has completed.
    ///
    /// The notification name is defined by `NCGlobal.shared.notificationCenterUserInteractionMonitor`
    func handle(event: UIEvent) {
        guard event.type == .touches else { return }
        guard let touches = event.allTouches, !touches.isEmpty else { return }

        let allEnded = touches.allSatisfy {
            $0.phase == .ended || $0.phase == .cancelled
        }

        if allEnded {
            NotificationCenter.default.post(name: Notification.Name(rawValue: NCGlobal.shared.notificationCenterUserInteractionMonitor), object: nil, userInfo: nil)
        }
    }
}
